FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm ci

FROM base AS development

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

FROM base AS build

ARG VITE_STOCK_ASSETS_API_BASE_URL=""
ARG VITE_STOCK_FACTOR_COEFVEC_API_BASE_URL=""
ARG VITE_STOCK_FUNDAMENTAL_API_BASE_URL=""
ARG VITE_LOCAL_BACKEND_SERVER=""

ENV VITE_STOCK_ASSETS_API_BASE_URL=${VITE_STOCK_ASSETS_API_BASE_URL}
ENV VITE_STOCK_FACTOR_COEFVEC_API_BASE_URL=${VITE_STOCK_FACTOR_COEFVEC_API_BASE_URL}
ENV VITE_STOCK_FUNDAMENTAL_API_BASE_URL=${VITE_STOCK_FUNDAMENTAL_API_BASE_URL}
ENV VITE_LOCAL_BACKEND_SERVER=${VITE_LOCAL_BACKEND_SERVER}

COPY . .

RUN npm run build

FROM nginx:1.27-alpine AS production

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
