export const textContent = {
  // Navigation
  "navigation-logo-alt": "Smooth Path Investing Logo",
  "navigation-brand-name": "Smooth Path Investing",
  "navigation-approach": "Our Approach",
  "navigation-backtests": "Backtests",
  "navigation-stocks": "Recommended Stocks",
  "navigation-about": "About Us",
  "navigation-login": "Login",

  // Home - Hero Section
  "home-hero-title": "Smarter Stock Picks",
  "home-hero-subtitle": "Make institutional stock investment available to retail investors",

  // Home - Mission Section
  "home-mission-title": "Our Mission",
  "home-mission-subtitle": "Transforming institutional-grade investment strategies for every investor",
  "home-mission-point-1": "Create a money-making engine from the growth of companies and economies.",
  "home-mission-point-2": "Integrate common sense, math, risk budgets, market expertise and reflections.",
  "home-mission-point-3-prefix": "Offer A-to-Z stock investing, from signals to portfolios in your pocket, ",
  "home-mission-point-4": "Order, segregate, integrate, condition, exclude, and concentrate",

  // Home - Stats Section
  "home-stats-button-explore": "Explore Our Picks",
  "home-stats-button-method": "See Our Method",
  "home-stats-or": "or",
  "home-stats-annual-return": "23.4%",
  "home-stats-annual-return-label": "Annual Return",
  "home-stats-sharpe-ratio": "1.42",
  "home-stats-sharpe-ratio-label": "Sharpe Ratio",
  "home-stats-win-rate": "68%",
  "home-stats-win-rate-label": "Win Rate",
  "home-stats-max-drawdown": "-8.2%",
  "home-stats-max-drawdown-label": "Max Drawdown",
  "home-stats-trust-backtested": "Backtested since 2015",
  "home-stats-trust-portfolios": "10,000+ simulated portfolios",
  "home-stats-trust-disclaimer": "*Past performance does not guarantee future results",

  // Home - Methodology Section
  "home-methodology-title": "Our Methodology",
  "home-methodology-subtitle": "Combining traditional financial analysis with cutting-edge AI to identify the best investment opportunities in today's markets.",
  "home-methodology-factor-title": "Factor Models",
  "home-methodology-factor-description": "Multi-factor quantitative analysis of fundamentals, technicals, and sentiment to identify undervalued opportunities",
  "home-methodology-ai-title": "AI Signals",
  "home-methodology-ai-description": "Machine learning algorithms processing vast market datasets to predict price movements and trends",
  "home-methodology-backtested-title": "Backtested Rules",
  "home-methodology-backtested-description": "Rigorously tested investment rules with 10+ years of validation and proven risk-adjusted returns",
  "home-methodology-button": "Learn More About Our Approach",

  // Home - Performance Section
  "home-performance-title": "Proven Performance",
  "home-performance-subtitle": "Our track record speaks for itself. Consistent outperformance through systematic, data-driven investment strategies.",

  // Home - Trust Section
  "home-trust-title": "Built on Trust & Transparency",
  "home-trust-subtitle": "No hidden fees, no aggressive upselling, no cluttered interfaces. Just clear insights and honest performance tracking.",
  "home-trust-transparency-title": "Full Transparency",
  "home-trust-transparency-description": "Complete methodology disclosure and performance tracking",
  "home-trust-upselling-title": "No Upselling",
  "home-trust-upselling-description": "Soft CTAs and genuine value, not pressure tactics",
  "home-trust-mobile-title": "Mobile First",
  "home-trust-mobile-description": "Fast, responsive design that works on any device",
  "home-trust-design-title": "Clean Design",
  "home-trust-design-description": "No clutter, just the insights that matter",

  // About Page
  "about-page-title": "Meet the Team",
  "about-page-subtitle": "Our team combines deep expertise in quantitative finance, mathematics, and risk management from top-tier institutions around the world.",
  "about-page-profile-view": "View Profile",
  "about-page-footer": "Each team member brings unique perspectives from top-tier institutions, ensuring our research methodology reflects the best practices from academia and industry.",

  // About - Mission & Vision
  "about-mission-title": "Our Mission",
  "about-mission-text-1": "To democratize sophisticated investment research by making institutional-grade analysis accessible to every investor, regardless of their experience level.",
  "about-mission-text-2": "We believe that transparency, rigorous methodology, and user-friendly design should be the foundation of modern investment platforms.",
  "about-mission-text-3": "Our goal is to level the playing field between retail and institutional investors by providing the same caliber of research and analysis tools.",
  "about-sets-apart-title": "What Sets Us Apart",
  "about-sets-apart-transparency-title": "Transparency First",
  "about-sets-apart-transparency-description": "Complete methodology disclosure and real performance tracking",
  "about-sets-apart-results-title": "Proven Results",
  "about-sets-apart-results-description": "Rigorous backtesting with 10+ years of validated performance",
  "about-sets-apart-agenda-title": "No Hidden Agenda",
  "about-sets-apart-agenda-description": "No aggressive upselling or cluttered interfaces",
  "about-sets-apart-design-title": "User-Centric Design",
  "about-sets-apart-design-description": "Built for investors, by investors who understand your needs",
  "about-vision-title": "Our Vision",
  "about-vision-text": "To become the most trusted source of investment research globally, where every recommendation is backed by rigorous data analysis and where transparency isn't just a promise—it's our fundamental operating principle.",

  // About - Core Values
  "about-values-title": "Our Core Values",
  "about-values-simplicity-title": "Simplicity",
  "about-values-simplicity-description": "Complex strategies made simple. We believe powerful tools should be easy to understand and use.",
  "about-values-integrity-title": "Integrity",
  "about-values-integrity-description": "Honest reporting, transparent methodology, and putting our users' interests first, always.",
  "about-values-performance-title": "Performance",
  "about-values-performance-description": "Results speak louder than promises. Every recommendation is backed by rigorous data analysis.",
  "about-values-innovation-title": "Innovation",
  "about-values-innovation-description": "Continuously pushing boundaries in financial technology and investment research.",

  // About - How We Operate
  "about-operate-title": "How We Operate",
  "about-operate-global-title": "Global Perspective",
  "about-operate-global-description": "We analyze markets worldwide, incorporating global trends and cross-market insights to provide comprehensive investment recommendations.",
  "about-operate-quality-title": "Quality Over Quantity",
  "about-operate-quality-description": "We focus on fewer, higher-conviction picks rather than overwhelming users with hundreds of mediocre recommendations.",
  "about-operate-user-first-title": "User-First Approach",
  "about-operate-user-first-description": "Every decision we make is evaluated through the lens of user benefit, not short-term revenue maximization.",
  "about-commitment-title": "Our Commitment to You",
  "about-commitment-1": "Never charge hidden fees or surprise costs",
  "about-commitment-2": "Provide complete transparency in our methodology",
  "about-commitment-3": "Continuously improve based on user feedback",
  "about-commitment-4": "Maintain the highest standards of data security",
  "about-commitment-5": "Support responsible investing practices",

  // About - Our Story
  "about-story-title": "Our Story",
  "about-story-text-1": "Founded by a team of quantitative analysts and technology experts who were frustrated with the existing landscape of investment research platforms. We saw too many services that prioritized marketing over methodology, complexity over clarity.",
  "about-story-text-2": "Smooth Path Investing was born from a simple idea: what if investment research could be both sophisticated and accessible? What if transparency wasn't just a buzzword, but the foundation of everything we do?",
  "about-story-text-3": "After years in traditional finance, seeing how the best research was hoarded by institutions, we decided to build something different. A platform where retail investors could access the same quality of analysis that was previously reserved for hedge funds and pension funds.",
  "about-story-text-4": "Today, we're proud to serve thousands of investors worldwide, from beginners taking their first steps into the market to experienced traders looking for an edge. Our commitment remains the same: provide the best possible research with complete transparency.",

  // About - Awards
  "about-awards-title": "Awards & Recognition",
  "about-awards-fintech-title": "FinTech Innovation Award",
  "about-awards-fintech-year": "2023",
  "about-awards-fintech-description": "Recognized for democratizing institutional-grade investment research",
  "about-awards-ux-title": "Best User Experience",
  "about-awards-ux-year": "Investment Platform Awards 2023",
  "about-awards-ux-description": "Leading in user interface design and accessibility",
  "about-awards-performance-title": "Top Performance",
  "about-awards-performance-year": "Independent Research Review 2023",
  "about-awards-performance-description": "Highest risk-adjusted returns among peer platforms",

  // About - Contact
  "about-contact-title": "Get in Touch",
  "about-contact-subtitle": "Have questions about our methodology, want to partner with us, or just want to say hello? We'd love to hear from you.",
  "about-contact-general-label": "General Inquiries",
  "about-contact-general-email": "hello@smoothpathinvesting.com",
  "about-contact-research-label": "Research Team",
  "about-contact-research-email": "research@smoothpathinvesting.com",
  "about-contact-partnerships-label": "Partnerships",
  "about-contact-partnerships-email": "partners@smoothpathinvesting.com",

  // Approach Page
  "approach-page-title": "Our Investment Approach",
  "approach-page-subtitle": "Discover how we combine cutting-edge technology with proven investment principles to identify winning stocks with institutional-grade precision",
  "approach-section-title": "Our Approach",
  "approach-research-title": "Research Documents",
  "approach-research-stories-title": "SPI Stock Stories",
  "approach-research-stories-description": "Real-world case studies and practical applications of our SPI methodology",
  "approach-research-paper1-title": "Research Paper #1",
  "approach-research-paper1-description": "Academic research supporting our quantitative methodology",
  "approach-research-paper2-title": "Research Paper #2",
  "approach-research-paper2-description": "Technical analysis and validation of our AI-driven signals",
  "approach-research-button-text": "View Document",
  "approach-research-button-paper": "View Paper",
  "approach-research-coming-soon": "(Coming Soon)",
  "approach-implications-title": "Practical Implications of SPI Implementations",

  // Performance Page
  "performance-page-title": "Historical Performance",
  "performance-page-subtitle": "Transparency through data - see how our strategies have performed over time with complete accountability",
  "performance-kpi-title": "Key Performance Indicators",
  "performance-information-ratio-title": "Information Ratio",
  "performance-information-ratio-value": "1.34",
  "performance-information-ratio-vs": "vs Benchmark 0.82",
  "performance-max-drawdown-title": "Maximum Drawdown",
  "performance-max-drawdown-value": "-8.2%",
  "performance-max-drawdown-vs": "vs S&P 500 -19.6%",
  "performance-hit-rate-title": "Hit Rate",
  "performance-hit-rate-value": "68.4%",
  "performance-hit-rate-description": "Winning positions",
  "performance-positive-months-title": "Positive Months",
  "performance-positive-months-value": "78%",
  "performance-positive-months-description": "Over 5 years",
  "performance-annual-breakdown-title": "Annual Performance Breakdown",
  "performance-table-year": "Year",
  "performance-table-smooth-path": "Smooth Path",
  "performance-table-sp500": "S&P 500",
  "performance-table-outperformance": "Outperformance",
  "performance-table-volatility": "Volatility",
  "performance-tab-overall": "Overall Performance",
  "performance-tab-sector": "Sector Performance",
  "performance-tab-risk": "Risk Metrics",
  "performance-tab-attribution": "Performance Attribution",
  "performance-tab-overall-desc": "Cumulative returns compared to major benchmarks including transaction costs",
  "performance-tab-sector-desc": "Performance breakdown by industry sectors and market cap categories",
  "performance-tab-risk-desc": "Risk-adjusted metrics, volatility analysis, and drawdown characteristics",
  "performance-tab-attribution-desc": "Factor decomposition showing sources of outperformance",
  "performance-risk-analysis-title": "Risk Analysis",
  "performance-downside-title": "Downside Protection",
  "performance-downside-bear-market": "Bear Market Performance (2022)",
  "performance-downside-bear-value": "-8.1% vs -18.1%",
  "performance-downside-deviation": "Downside Deviation",
  "performance-downside-deviation-value": "8.7%",
  "performance-downside-sortino": "Sortino Ratio",
  "performance-downside-sortino-value": "2.14",
  "performance-downside-calmar": "Calmar Ratio",
  "performance-downside-calmar-value": "2.86",
  "performance-portfolio-characteristics-title": "Portfolio Characteristics",
  "performance-portfolio-beta": "Beta vs S&P 500",
  "performance-portfolio-beta-value": "0.87",
  "performance-portfolio-correlation": "Correlation with Market",
  "performance-portfolio-correlation-value": "0.81",
  "performance-portfolio-tracking-error": "Tracking Error",
  "performance-portfolio-tracking-error-value": "7.3%",
  "performance-portfolio-position-size": "Average Position Size",
  "performance-portfolio-position-size-value": "3.2%",
  "performance-backtest-title": "Rigorous Backtesting Methodology",
  "performance-backtest-subtitle": "Our strategies are validated against 10+ years of historical data using institutional-grade testing protocols",
  "performance-backtest-years": "10+",
  "performance-backtest-years-title": "Years of Data",
  "performance-backtest-years-description": "Comprehensive testing across multiple market cycles including bull markets, bear markets, and sideways trends",
  "performance-backtest-stocks": "500+",
  "performance-backtest-stocks-title": "Stocks Analyzed",
  "performance-backtest-stocks-description": "Broad universe testing across different market capitalizations, sectors, and geographic regions",
  "performance-backtest-confidence": "95%",
  "performance-backtest-confidence-title": "Confidence Level",
  "performance-backtest-confidence-description": "Statistical significance in out-of-sample testing protocols with proper train/validation/test splits",
  "performance-backtest-framework-title": "Testing Framework",
  "performance-backtest-framework-1": "Walk-forward analysis with rolling windows",
  "performance-backtest-framework-2": "Out-of-sample validation periods",
  "performance-backtest-framework-3": "Monte Carlo simulations for robustness",
  "performance-backtest-framework-4": "Transaction cost modeling",
  "performance-backtest-realism-title": "Market Realism",
  "performance-backtest-realism-1": "Realistic slippage assumptions",
  "performance-backtest-realism-2": "Market impact calculations",
  "performance-backtest-realism-3": "Proper trade execution timing",
  "performance-backtest-realism-4": "Survivorship bias elimination",
  "performance-simulator-title": "Portfolio Strategy Simulator",
  "performance-simulator-description": "Test your own portfolio strategies with our backtesting engine. Upload your allocation strategy and see how it would have performed historically.",
  "performance-simulator-capital-label": "Initial Capital",
  "performance-simulator-capital-helper": "Starting portfolio value in USD",
  "performance-simulator-strategy-label": "Portfolio Strategy (CSV)",
  "performance-simulator-strategy-helper": "Upload rebalancing dates, tickers, and weights",
  "performance-simulator-example-button": "Load Example",
  "performance-simulator-run-button": "Run Backtest",
  "performance-simulator-format-title": "Expected CSV Format:",
  "performance-simulator-format-line1": "Start Date,Assets,Weights",
  "performance-simulator-format-line2": "1/1/2023,\"AAPL, MSFT, GOOGL\",\"40%, 30%, 30%\"",
  "performance-simulator-note": "Note: This is a simplified simulator using mock price data. Actual results may vary based on real market conditions, transaction costs, and other factors.",
  "performance-simulator-load-toast-title": "Example Loaded",
  "performance-simulator-load-toast-description": "Sample portfolio strategy loaded into the simulator",
  "performance-simulator-error-empty-title": "Error",
  "performance-simulator-error-empty-description": "Please enter strategy CSV data",
  "performance-simulator-error-no-rows-description": "No valid strategy rows found in CSV",
  "performance-simulator-complete-title": "Backtest Complete",

  // Pricing Page
  "pricing-page-title": "Choose Your Plan",
  "pricing-page-subtitle": "Get access to AI-powered stock recommendations and professional-grade investment tools",
  "pricing-plan-popular": "Most Popular",
  "pricing-plan-included": "Included:",
  "pricing-plan-not-included": "Not included:",
  "pricing-enterprise-title": "Need a Custom Solution?",
  "pricing-enterprise-description": "Enterprise plans available with custom integrations, dedicated infrastructure, and personalized support.",
  "pricing-enterprise-button": "Contact Enterprise Sales",

  // Stocks Page
  "stocks-page-title": "Recommended Stocks",
  "stocks-page-subtitle": "Our AI-powered analysis has identified these high-potential opportunities based on rigorous quantitative research and backtested strategies",
  "stocks-portfolio-title": "Current Portfolio Overview",
  "stocks-portfolio-positions": "Active Positions",
  "stocks-portfolio-positions-value": "12",
  "stocks-portfolio-performance": "YTD Performance",
  "stocks-portfolio-performance-value": "+23.4%",
  "stocks-portfolio-win-rate": "Win Rate",
  "stocks-portfolio-win-rate-value": "68%",
  "stocks-portfolio-sharpe": "Sharpe Ratio",
  "stocks-portfolio-sharpe-value": "1.42",
  "stocks-featured-title": "Featured Picks",
  "stocks-featured-badge": "Featured",
  "stocks-thesis-title": "Investment Thesis",
  "stocks-thesis-suffix": "Our analysis shows strong fundamentals combined with attractive valuation metrics.",
  "stocks-catalysts-title": "Key Catalysts",
  "stocks-view-analysis": "View Detailed Analysis",
  "stocks-filter-all": "All Picks",
  "stocks-filter-high-conviction": "High Conviction",
  "stocks-filter-value": "Value Plays",
  "stocks-filter-growth": "Growth Stories",
  "stocks-filter-momentum": "Momentum",
  "stocks-sort-conviction": "Conviction Level",
  "stocks-sort-performance": "Recent Performance",
  "stocks-sort-alphabetical": "Alphabetical",
  "stocks-sort-sector": "Sector",
  "stocks-search-placeholder": "Search stocks...",

  // Access Denied
  "access-denied-title": "Premium Stock Recommendations",
  "access-denied-subtitle": "Access our AI-powered stock picks with a Pro or Elite subscription",
  "access-denied-unlock-title": "Unlock Premium Features",
  "access-denied-unlock-description": "Get access to our carefully curated stock recommendations, advanced analytics, and real-time alerts with a Pro or Elite subscription.",
  "access-denied-feature-1": "AI-powered stock analysis",
  "access-denied-feature-2": "Real-time market alerts",
  "access-denied-feature-3": "Advanced portfolio analytics",
  "access-denied-button-signup": "Sign Up Now",
  "access-denied-button-upgrade": "Upgrade to Pro",
  "access-denied-button-pricing": "View Pricing",

  // Premium Stocks Hidden
  "premium-hidden-title": "Premium Stocks Hidden",
  "premium-hidden-description": "Premium stock features are currently hidden for testing purposes. Click on your profile in the navigation to toggle them back on.",
  "premium-hidden-button": "Show Premium Stocks",

  // Not Found Page
  "notfound-title": "404",
  "notfound-message": "Oops! Page not found",
  "notfound-link": "Return to Home",
};
